server.port=8080

spring.application.name=task-manager-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_manager_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:very-secret-key-for-jwt-token-change-later-very-long}
jwt.expiration=${JWT_EXPIRATION:86400000}
openrouter.api.key="???? ??????"
openrouter.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=deepseek/deepseek-chat-v3-0324